---
- name: Freeradius installation and configuration
  hosts: server-freeradius
  remote_user: root
  # become: yes
  # become_method: sudo

  roles:
    - common
    - { role: postgresql, when: database == 'postgresql' }
    - { role: mysql, when: database == 'mysql' }